import { Report } from "@/types/report";

export const mockReports: Report[] = [
  {
    id: "1",
    title: "AC Ruang Kelas Rusak",
    description: "AC di ruang kelas A-201 tidak berfungsi, suhu ruangan sangat panas dan mengganggu proses belajar mengajar.",
    category: "classroom",
    location: "Gedung A, Lantai 2, Ruang 201",
    photoUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    status: "in_progress",
    reporterName: "Budi Santoso",
    reporterEmail: "budi@student.ac.id",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-16"),
    adminNote: "Teknisi sudah dihubungi, akan diperbaiki dalam 2 hari.",
  },
  {
    id: "2",
    title: "Lampu Perpustakaan Mati",
    description: "Beberapa lampu di area baca perpustakaan lantai 3 tidak menyala, membuat area tersebut kurang terang untuk membaca.",
    category: "library",
    location: "Perpustakaan Pusat, Lantai 3",
    photoUrl: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800",
    status: "completed",
    reporterName: "Siti Aminah",
    reporterEmail: "siti@student.ac.id",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-12"),
    adminNote: "Lampu sudah diganti dan berfungsi normal.",
  },
  {
    id: "3",
    title: "Toilet Tersumbat",
    description: "Toilet pria lantai 1 gedung B mengalami penyumbatan dan air tidak bisa mengalir dengan baik.",
    category: "toilet",
    location: "Gedung B, Lantai 1",
    photoUrl: "https://images.unsplash.com/photo-1584622781867-7d8f964c9d5d?w=800",
    status: "pending",
    reporterName: "Ahmad Wijaya",
    reporterEmail: "ahmad@student.ac.id",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "4",
    title: "Proyektor Lab Komputer Error",
    description: "Proyektor di lab komputer 1 menampilkan gambar yang blur dan kadang mati sendiri saat presentasi.",
    category: "laboratory",
    location: "Lab Komputer 1, Gedung C",
    status: "in_progress",
    reporterName: "Dewi Lestari",
    reporterEmail: "dewi@student.ac.id",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-15"),
    adminNote: "Sedang dalam pengecekan, kemungkinan perlu penggantian lampu proyektor.",
  },
  {
    id: "5",
    title: "Lapangan Basket Retak",
    description: "Lantai lapangan basket outdoor mengalami keretakan di beberapa bagian dan berbahaya untuk bermain.",
    category: "sports_facility",
    location: "Lapangan Olahraga Outdoor",
    photoUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
    status: "pending",
    reporterName: "Rudi Hartono",
    reporterEmail: "rudi@student.ac.id",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "6",
    title: "Meja Kantin Patah",
    description: "Salah satu meja di area kantin mengalami kerusakan pada kakinya sehingga tidak stabil untuk digunakan.",
    category: "canteen",
    location: "Kantin Utama",
    status: "completed",
    reporterName: "Lisa Permata",
    reporterEmail: "lisa@student.ac.id",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-10"),
    adminNote: "Meja sudah diperbaiki dan dapat digunakan kembali.",
  },
];
